// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tags.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const associateTagWithPost = `-- name: AssociateTagWithPost :exec
insert into posts_tags (id, post_id, tag_id) values ($1, $2, $3)
`

type AssociateTagWithPostParams struct {
	ID     uuid.UUID
	PostID uuid.UUID
	TagID  uuid.UUID
}

func (q *Queries) AssociateTagWithPost(ctx context.Context, arg AssociateTagWithPostParams) error {
	_, err := q.db.Exec(ctx, associateTagWithPost, arg.ID, arg.PostID, arg.TagID)
	return err
}

const deleteTagsFromPost = `-- name: DeleteTagsFromPost :exec
delete from posts_tags
where post_id = $1
`

func (q *Queries) DeleteTagsFromPost(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTagsFromPost, postID)
	return err
}

const insertTag = `-- name: InsertTag :exec
insert into tags (id, name)
values ($1, $2)
`

type InsertTagParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.Exec(ctx, insertTag, arg.ID, arg.Name)
	return err
}

const queryAllTags = `-- name: QueryAllTags :many
select id, name
from tags
`

func (q *Queries) QueryAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, queryAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryTagsByIDs = `-- name: QueryTagsByIDs :many
select id, name
from tags
where id in ($1::uuid[])
`

func (q *Queries) QueryTagsByIDs(ctx context.Context, tagIds []uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, queryTagsByIDs, tagIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryTagsByPost = `-- name: QueryTagsByPost :many
select tags.id, tags.name
from tags
left join posts_tags on posts_tags.tag_id = tags.id
where posts_tags.post_id = $1
`

func (q *Queries) QueryTagsByPost(ctx context.Context, postID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, queryTagsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
