// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/MBvisti/mortenvistisen/views/layouts"

func ProjectsPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row mt-5 d-flex flex-column\"><h1 class=\"text-white col text-center fw-semibold mb-5\">Projects</h1><div class=\"col col-md-6 mx-auto\"><div class=\"text-white bg-body p-4 mb-5\"><h2 class=\"fw-semibold\">YouTube</h2><p class=\"mb-2\">I've long wanted to get into creating video tutorials and content.</p><p class=\"mb-2\">mbv-labs is meant to be the start of that journey; the channel will contain tutorials, but also videos building features/fixing problems/etc for my other side projects, which can contain code but also higher level discussions on indiehacking and building software.</p><a rel=\"nofollow\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL = templ.SafeURL("https://www.youtube.com/@mbvisti")
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var3)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><button data-umami-event=\"projects--youtube-mbv-labs\" class=\"btn bg-primary mt-2\">Check it out</button></a></div><div class=\"text-white bg-body p-4 mb-5\"><h2 class=\"fw-semibold\">Grafto</h2><p class=\"mb-2\">After hating on php for a long time I finally took some time out to try  it out, more specifically Laravel. Boy was I wrong about php.</p><p class=\"mb-2\">Laravel is such a great framework with (almost) everything you need out of the box. But I love writing Go, and I've spend too much time in statically typed  languages that going back to dynamically typed languages is a no-go for me.</p><p class=\"mb-2\">So, I decided to built my own Laravel inspired version in Go which I've called Grafto. It's more of a boilerplate than a framework, but it's a great starting point for building</p><p class=\"mb-2\">Aimed at indiehackers wanting to ship products fully in Go.</p><p class=\"mb-2\">Uses: Go, templ, tailwindcss, daisyui, alpine.js and htmx.</p><a rel=\"nofollow\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL = templ.SafeURL("https://www.github.com/mbvisti/mortenvistisen")
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var4)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><button data-umami-event=\"projects--youtube-mbv-labs\" class=\"btn bg-primary mt-2\">Check it out</button></a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(Head(
			ctx, WithTitle("Projects"),
			WithDescription("A collection of all projects, past and on-going, that I'm working on. Mainly content creation and one-man businesses."),
		)).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
