// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/MBvisti/mortenvistisen/views/layouts"
	"github.com/dromara/carbon/v2"
	"io"
	"time"
	"unicode/utf8"
)

type ArticlePageData struct {
	Title             string
	Slug              string
	Content           string
	HeaderTitle       string
	CsrfToken         string
	ReleaseDate       time.Time
	OtherArticleLinks map[string]string
}

func unsafe(html string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, html)
		return
	})
}

func renderSubscribeForm(csrfToken, title, slugTitle string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_renderSubscribeForm_c956`,
		Function: `function __templ_renderSubscribeForm_c956(csrfToken, title, slugTitle){const targetDiv = document.querySelector("#subscribe-form");

	targetDiv.innerHTML = ` + "`" + `
  ` + "`" + `;
}`,
		Call:       templ.SafeScript(`__templ_renderSubscribeForm_c956`, csrfToken, title, slugTitle),
		CallInline: templ.SafeScriptInline(`__templ_renderSubscribeForm_c956`, csrfToken, title, slugTitle),
	}
}

func triggerModal(articleName string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_triggerModal_051c`,
		Function: `function __templ_triggerModal_051c(articleName){const headers = document.querySelectorAll("h2");
		let targetHeaderNum = 0

		if (headers.length == 0) {
			return
		};
		
		if (headers.length > 2) {
			targetHeaderNum = Math.ceil(headers.length*2/3)
		};

		headers[targetHeaderNum].insertAdjacentHTML(
			"beforeBegin", 
			` + "`" + `<div hx-swap="outerHTML" hx-target="this" hx-get="/modal?article-name=${articleName}" 
			hx-trigger="revealed"></div>` + "`" + `
		);
}`,
		Call:       templ.SafeScript(`__templ_triggerModal_051c`, articleName),
		CallInline: templ.SafeScriptInline(`__templ_triggerModal_051c`, articleName),
	}
}

func truncateSlug(slug string, maxLength int) string {
	// Calculate the rune count in the slug
	runeCount := utf8.RuneCountInString(slug)

	// If the slug is within the allowed length, return it as is
	if runeCount <= maxLength {
		return slug
	}

	// If the slug is longer, truncate it to the allowed length
	runes := []rune(slug)
	truncatedSlug := string(runes[:maxLength])

	return truncatedSlug
}

func triggerCourse(article string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_triggerCourse_13a2`,
		Function: `function __templ_triggerCourse_13a2(article){const headers = document.querySelectorAll("h2");
		let targetHeaderNum = 0

		headers[targetHeaderNum].insertAdjacentHTML(
				"beforeBegin", 
				` + "`" + `<div class="bg-body p-4 my-4">
						<p class="fw-semibold fs-4">I'm building a course!</p>
						<p class="fs-6">
							Sorry to interrupt, I'm working on a course that shows you to build modern web apps using Golang, HTMX and Templ.
						</p>
						<p class="fs-6">
							If you want to learn how to build a professional blog with Go, like this one, check it out: 
						</p>
						<a
							data-umami-event="course--golang-blog-course-article"
							class="btn bg-primary"
							href="https://golangblogcourse.com?ref=mortenvistisen.com/${article}"
							target="_blank"
						>Here</a>
				</div>
				` + "`" + `
		);
}`,
		Call:       templ.SafeScript(`__templ_triggerCourse_13a2`, article),
		CallInline: templ.SafeScriptInline(`__templ_triggerCourse_13a2`, article),
	}
}

func ArticlePage(data ArticlePageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"d-none d-sm-block position-fixed top-10\"><a href=\"/\" aria-label=\"Go back\" class=\"text-white\" x-data=\"{ isHovered: false }\" @mouseenter=\"isHovered = true\" @mouseleave=\"isHovered = false\"><svg x-show=\"isHovered\" x-transition xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-arrow-left-short\" viewBox=\"0 0 16 16\"><path fill-rule=\"evenodd\" d=\"M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5\"></path></svg> Back</a></div><div class=\"row mt-5\"><div class=\"col col-md-7 mx-auto\"><div class=\"text-center\"><h1 class=\"fw-semibold\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/article.templ`, Line: 109, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1><p class=\"fs-6\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(carbon.CreateFromStdTime(data.ReleaseDate).ToDateString())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/article.templ`, Line: 111, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " by mbv</p></div><article class=\"fs-5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = unsafe(data.Content).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<hr><div class=\"mt-10\"><p class=\"text-neutral-content\">Thanks for reading. </p><p>If you enjoyed this one you can check one some of these:</p><ul class=\"list-disc list-outside\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for title, slug := range data.OtherArticleLinks {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<li><a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 templ.SafeURL = templ.URL(slug)
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var5)))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"text-neutral-content text-base hover:text-teal-700\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(title)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/article.templ`, Line: 128, Col: 17}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</a></li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</ul></div></article></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = triggerCourse(data.Slug).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(Head(ctx, WithTitle(data.HeaderTitle))).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
