// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"github.com/MBvisti/mortenvistisen/views/internal/layouts"
	"github.com/golang-module/carbon/v2"
	"github.com/gosimple/slug"
	"time"
	"unicode/utf8"
)

type ArticlePageData struct {
	Content           string
	Title             string
	CsrfToken         string
	ReleaseDate       time.Time
	OtherArticleLinks map[string]string
}

func unsafe(html string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, html)
		return
	})
}

func renderSubscribeForm(csrfToken, title, slugTitle string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_renderSubscribeForm_d1fb`,
		Function: `function __templ_renderSubscribeForm_d1fb(csrfToken, title, slugTitle){const targetDiv = document.querySelector("#subscribe-form");

	targetDiv.innerHTML = ` + "`" + `
		<div class="max-w-xl text-center mx-auto">
			<div class="mb-5">
				<h3 class="text-2xl font-bold md:text-3xl md:leading-tight text-white">Monthly technical deep dives.</h3>
				<p class="text-base">I work with everything from backend dev, systems designs to devops and machine learning. I share my learnings twice a month in tutorial form, so you can pick up new concept faster and expand your technical tool belt.</p>
  			</div>
  			<form hx-post="/subscribe" hx-target="this" hx-swap="outerHTML" method="POST" action="/subscribe" >
				<input type="hidden" name="gorilla.csrf.Token" value="${csrfToken}"/>
				<div class="mt-5 lg:mt-8 flex flex-col items-center gap-2 sm:flex-row sm:gap-3">
					<input type="hidden" name="article-title" value="${title}"/>
					<input required type="email" id="hero-input" name="hero-input" class="py-3 px-4 block w-full border-gray-200 rounded-lg 
  				          text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none 
  				          bg-slate-900 border-gray-700 text-gray-400 focus:ring-gray-600" placeholder="deep-dives@mortenvistisen.com" />
  				      <button data-umami-event="newsletter--${slugTitle}" type="submit" class="w-full sm:w-auto whitespace-nowrap py-3 px-4 inline-flex justify-center 
  				          items-center gap-x-2 text-sm font-semibold rounded-lg border bg-slate-600 
  				          text-white hover:bg-slate-900 disabled:opacity-50 disabled:pointer-events-none focus:outline-none 
  				          focus:ring-1 focus:ring-gray-600">
  				        Receive Tutorials
  				      </button>
  				</div>
			</form>
  		</div>
  ` + "`" + `;
}`,
		Call:       templ.SafeScript(`__templ_renderSubscribeForm_d1fb`, csrfToken, title, slugTitle),
		CallInline: templ.SafeScriptInline(`__templ_renderSubscribeForm_d1fb`, csrfToken, title, slugTitle),
	}
}

func triggerModal(articleName string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_triggerModal_8a55`,
		Function: `function __templ_triggerModal_8a55(articleName){const cookieValue = document.cookie
		.split("; ")
  		.find((row) => row.startsWith("hideModal="))
  		?.split("=")[1];

	if (cookieValue !== "true") {
		const headers = document.querySelectorAll("h2");
		headers[3].insertAdjacentHTML(
			"beforeBegin", 
			` + "`" + `<div hx-swap="outerHTML" hx-target="this" hx-get="/modal?article-name=${articleName}" 
			hx-trigger="revealed"></div>` + "`" + `
		);
	}
}`,
		Call:       templ.SafeScript(`__templ_triggerModal_8a55`, articleName),
		CallInline: templ.SafeScriptInline(`__templ_triggerModal_8a55`, articleName),
	}
}

func truncateSlug(slug string, maxLength int) string {
	// Calculate the rune count in the slug
	runeCount := utf8.RuneCountInString(slug)

	// If the slug is within the allowed length, return it as is
	if runeCount <= maxLength {
		return slug
	}

	// If the slug is longer, truncate it to the allowed length
	runes := []rune(slug)
	truncatedSlug := string(runes[:maxLength])

	return truncatedSlug
}

func ArticlePage(data ArticlePageData, head Head) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col md:grid md:grid-flow-col md:gap-y-8 md:grid-rows-[200px_1fr] md:grid-cols-12 \n			w-full px-4 md:px-0 md:w-2/3 mt-12 mx-auto hero\"><div class=\"w-full col-start-3 col-end-11 row-start-1 row-end-2 flex flex-col\"><h1 class=\"mx-auto text-center text-6xl mb-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/article.templ`, Line: 93, Col: 62}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><div class=\"flex mx-auto text-xl\"><p class=\"text-gray-500 mr-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%s %v, %v", carbon.CreateFromStdTime(data.ReleaseDate).ToShortMonthString(),
				carbon.CreateFromStdTime(data.ReleaseDate).DayOfMonth(), carbon.CreateFromStdTime(data.ReleaseDate).Year()))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/article.templ`, Line: 97, Col: 109}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><p class=\"text-gray-500 mr-2\">|</p><p class=\"text-gray-500\">MBV</p></div></div><article class=\"col-start-3 col-end-11 text-left mb-6 leading-normal prose lg:prose-xl row-start-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = unsafe(data.Content).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"mt-10 pb-10\"><p>Thanks for reading. Please checkout some of my other articles, if you enjoyed this one:</p><ul>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for title, slug := range data.OtherArticleLinks {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 templ.SafeURL = templ.URL(slug)
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var5)))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"text-base text-blue-500 hover:text-blue-700\"><li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(title)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/article.templ`, Line: 112, Col: 19}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</li></a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</ul></div></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Title != "How to build a (simple) blog using Rust" {
				templ_7745c5c3_Err = renderSubscribeForm(data.CsrfToken, data.Title, truncateSlug(slug.Make(data.Title), 37)).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = triggerModal(data.Title).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(head.Build()).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
