// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/MBvisti/mortenvistisen/views/internal/layouts"

func ProjectsPage(head Head) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col text-center py-5 px-4 sm:px-6 md:px-32 2xl:px-56\"><h1 class=\"mb-12 block text-2xl font-bold text-white sm:text-4xl\">Projects</h1><div class=\"mx-auto card w-96 bg-base-300 shadow-xl mb-10\"><div class=\"card-body\"><div class=\"mb-4 w-full flex justify-center\"><h2 class=\"card-title\">YouTube - mbv labs</h2></div><p class=\"text-start mb-2\">I've long wanted to get into creating video tutorials and content.</p><p class=\"text-start mb-4\">mbv-labs is meant to be the start of that journey; the channel will contain tutorials, but also videos building features/fixing problems/etc for my other side projects, which can contain code but also higher level discussions on indiehacking and building software.</p><div class=\"card-actions justify-center\"><a rel=\"nofollow\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL = templ.SafeURL("https://www.youtube.com/@mbvlabs")
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var3)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><button data-umami-event=\"projects--youtube-mbv-labs\" class=\"btn btn-primary\">Check it out</button></a></div></div></div><div class=\"mx-auto card w-96 bg-base-300 shadow-xl mb-10\"><div class=\"card-body\"><div class=\"mb-4 w-full flex justify-center\"><h2 class=\"card-title\">Grafto - Go Boilerplate</h2></div><p class=\"text-start mb-2\">After hating on php for a long time I finally took some time out to try  it out, more specifically Laravel. Boy was I wrong about php.</p><p class=\"text-start mb-4\">Laravel is such a great framework with (almost) everything you need out of the box. But I love writing Go, and I've spend too much time in statically typed  languages that going back to dynamically typed languages is a no-go for me.</p><p class=\"text-start mb-4\">So, I decided to built my own Laravel inspired version in Go which I've called Grafto. It's more of a boilerplate than a framework, but it's a great starting point for building full-stack web applications in Go.</p><p class=\"text-start mb-4\">Aimed at indiehackers wanting to ship products fully in Go.<br><br>Uses: Go, templ, tailwindcss, daisyui, alpine.js and htmx.</p><div class=\"card-actions justify-center\"><a rel=\"nofollow\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL = templ.SafeURL("https://www.github.com/mbv-labs/grafto")
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var4)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><button data-umami-event=\"projects--github-grafto\" class=\"btn btn-primary\">Check it out</button></a></div></div></div><div class=\"mx-auto card w-96 bg-base-300 shadow-xl\"><div class=\"card-body\"><div class=\"mb-4 w-full flex justify-center\"><h2 class=\"card-title\">This Week On Reddit</h2></div><p class=\"text-start mb-2\">This is an early stage project meant to analyze which problems various communities on Reddit experience.</p><p class=\"text-start mb-4\">By aggregating multiple subreddits into a broader community (e.g. all subreddits related to EVs),  identifying posts where the user experience a pain point and analyzing all those as a whole, you  can achieve a more accurate understanding of the problems users face. Using this, you can build  more relevant products, content etc.</p><div class=\"card-actions justify-center\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 templ.SafeURL = templ.SafeURL("https://twor.mbv-labs.com")
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var5)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><button data-umami-event=\"projects--this-week-on-reddit\" class=\"btn btn-primary\">Check it out</button></a></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(head.Build()).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
