// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Job struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ScheduledFor   time.Time
	FailedAttempts int32
	State          int32
	Instructions   pgtype.JSONB
	Executor       string
	RepeatableID   sql.NullString
}

type Post struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Title      string
	Filename   string
	Slug       string
	Excerpt    string
	Draft      bool
	ReleasedAt sql.NullTime
	ReadTime   sql.NullInt32
}

type PostsTag struct {
	ID     uuid.UUID
	PostID uuid.UUID
	TagID  uuid.UUID
}

type Tag struct {
	ID   uuid.UUID
	Name string
}

type Token struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Hash      string
	ExpiresAt time.Time
	Scope     string
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Mail           string
	MailVerifiedAt sql.NullTime
	Password       string
}
