// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: subscribers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSubscriberEmail = `-- name: ConfirmSubscriberEmail :exec
update subscribers set is_verified=true, updated_at=$2 where id=$1
`

type ConfirmSubscriberEmailParams struct {
	ID        uuid.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ConfirmSubscriberEmail(ctx context.Context, arg ConfirmSubscriberEmailParams) error {
	_, err := q.db.Exec(ctx, confirmSubscriberEmail, arg.ID, arg.UpdatedAt)
	return err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
delete from subscribers where id=$1
`

func (q *Queries) DeleteSubscriber(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriber, id)
	return err
}

const insertSubscriber = `-- name: InsertSubscriber :one
insert into subscribers 
	(id, created_at, updated_at, email, subscribed_at, referer, is_verified) 
values 
	($1, $2, $3, $4, $5, $6, $7)
returning id, created_at, updated_at, email, subscribed_at, referer, is_verified
`

type InsertSubscriberParams struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Email        sql.NullString
	SubscribedAt pgtype.Timestamptz
	Referer      sql.NullString
	IsVerified   pgtype.Bool
}

func (q *Queries) InsertSubscriber(ctx context.Context, arg InsertSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, insertSubscriber,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.SubscribedAt,
		arg.Referer,
		arg.IsVerified,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.SubscribedAt,
		&i.Referer,
		&i.IsVerified,
	)
	return i, err
}

const queryAllSubscribers = `-- name: QueryAllSubscribers :many
select id, created_at, updated_at, email, subscribed_at, referer, is_verified from subscribers
`

func (q *Queries) QueryAllSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, queryAllSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.SubscribedAt,
			&i.Referer,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryNewSubscribersForCurrentMonth = `-- name: QueryNewSubscribersForCurrentMonth :one
select 
	count(id) 
from 
	subscribers
where 
	 date_trunc('month', created_at) = date_trunc('month', current_timestamp)
`

func (q *Queries) QueryNewSubscribersForCurrentMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, queryNewSubscribersForCurrentMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const querySubscriber = `-- name: QuerySubscriber :one
select id, created_at, updated_at, email, subscribed_at, referer, is_verified from subscribers where id = $1
`

func (q *Queries) QuerySubscriber(ctx context.Context, id uuid.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, querySubscriber, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.SubscribedAt,
		&i.Referer,
		&i.IsVerified,
	)
	return i, err
}

const querySubscriberCount = `-- name: QuerySubscriberCount :one
select count(id) from subscribers
`

func (q *Queries) QuerySubscriberCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, querySubscriberCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const querySubscribersInPages = `-- name: QuerySubscribersInPages :many
select
	subscribers.id, subscribers.created_at, subscribers.updated_at, subscribers.email, subscribers.subscribed_at, subscribers.referer, subscribers.is_verified
from 
	subscribers
limit 
	$1
offset 
	$2
`

type QuerySubscribersInPagesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) QuerySubscribersInPages(ctx context.Context, arg QuerySubscribersInPagesParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, querySubscribersInPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.SubscribedAt,
			&i.Referer,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryUnverifiedSubCount = `-- name: QueryUnverifiedSubCount :one
select 
	count(id) 
from 
	subscribers
where
	is_verified = false
`

func (q *Queries) QueryUnverifiedSubCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, queryUnverifiedSubCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queryVerifiedSubscribers = `-- name: QueryVerifiedSubscribers :many
select id, created_at, updated_at, email, subscribed_at, referer, is_verified from subscribers where is_verified = true
`

func (q *Queries) QueryVerifiedSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, queryVerifiedSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.SubscribedAt,
			&i.Referer,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
