// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tags.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getTagsForPost = `-- name: GetTagsForPost :many
SELECT
    tags.id, tags.name
FROM
    tags
LEFT JOIN
    posts_tags ON posts_tags.tag_id = tags.id
WHERE
    posts_tags.post_id = $1
`

func (q *Queries) GetTagsForPost(ctx context.Context, postID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsForPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
