// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/MBvisti/grafto/views/internal/components"

func Base(content templ.Component, head components.Head) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\" class=\"dark h-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = head.Render().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"container mx-auto h-full bg-gray-800\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Nav().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/static/js/htmx.min.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script src=\"/static/js/alpine.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script src=\"/static/js/preline/preline.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

//type MetaComponent struct {
//	Name     string
//	Content  string
//	Property string
//}
//
//type Base struct {
//	MetaComponents []MetaComponent
//	HeaderTitle    string
//	Canonical      string
//}
//
//templ (b Base) Render(content templ.Component) {
//	<!DOCTYPE html>
//	<html lang="en" class="h-full">
//		<head>
//			<meta charset="UTF-8"/>
//			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
//			<meta name="twitter:card" content="summary_large_image"/>
//			<meta name="twitter:creator" content="@MBvisti"/>
//			<title>
//				switch b.HeaderTitle == "" {
//					case true:
//						Morten Vistisen
//					case false:
//						{ b.HeaderTitle } | Morten Vistisen
//					default:
//						Morten Vistisen
//				}
//			</title>
//			<link href="/static/css/output.css" rel="stylesheet"/>
//			<link rel="apple-touch-icon" sizes="180x180" href="/static/images/apple-touch-icon.png"/>
//			<link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon-32x32.png"/>
//			<link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicon-16x16.png"/>
//			for _, metaComponent := range b.MetaComponents {
//				<meta
// 					if metaComponent.Name != "" {
//						name={ metaComponent.Name }
//					}
// 					if metaComponent.Content != "" {
//						content={ metaComponent.Content }
//					}
// 					if metaComponent.Property != "" {
//						property={ metaComponent.Property }
//					}
//				/>
//			}
//			<link
// 				rel="canonical"
// 				href={ b.Canonical }
//			/>
//			if os.Getenv("ENVIRONMENT") == "production" {
//				<script async src="https://mbv-analytics.fly.dev/script.js" data-website-id="234f6bd6-823d-41e5-b84f-f351301f0e33"></script>
//			}
//		</head>
//		<body class="container mx-auto h-full bg-gray-800">
//			@components.Nav()
//			@content
//			<script src="/static/js/htmx.min.js"></script>
//			<script src="/static/js/alpine.js"></script>
//			<script src="/static/js/preline/preline.js"></script>
//		</body>
//	</html>
//}
