// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: analytics.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAnalytic = `-- name: InsertAnalytic :exec
insert into analytics (
    id,
    website_id,
    type,
    url,
    path,
    referrer,
    title,
    timestamp,
    screen,
    language,
    visitor_id,
    session_id,
    scroll_depth,
	real_ip
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type InsertAnalyticParams struct {
	ID          uuid.UUID
	WebsiteID   pgtype.UUID
	Type        sql.NullString
	Url         sql.NullString
	Path        sql.NullString
	Referrer    sql.NullString
	Title       sql.NullString
	Timestamp   pgtype.Timestamptz
	Screen      sql.NullString
	Language    sql.NullString
	VisitorID   pgtype.UUID
	SessionID   pgtype.UUID
	ScrollDepth sql.NullInt32
	RealIp      sql.NullString
}

func (q *Queries) InsertAnalytic(ctx context.Context, db DBTX, arg InsertAnalyticParams) error {
	_, err := db.Exec(ctx, insertAnalytic,
		arg.ID,
		arg.WebsiteID,
		arg.Type,
		arg.Url,
		arg.Path,
		arg.Referrer,
		arg.Title,
		arg.Timestamp,
		arg.Screen,
		arg.Language,
		arg.VisitorID,
		arg.SessionID,
		arg.ScrollDepth,
		arg.RealIp,
	)
	return err
}

const queryAnalyticsByDateRange = `-- name: QueryAnalyticsByDateRange :many
select 
	id, timestamp, website_id, type, url, path, referrer, title, screen, language, visitor_id, session_id, scroll_depth, real_ip 
from analytics 
where 
	website_id = $1 
and 
	timestamp between $2 and $3
order by 
	timestamp desc
`

type QueryAnalyticsByDateRangeParams struct {
	WebsiteID   pgtype.UUID
	Timestamp   pgtype.Timestamptz
	Timestamp_2 pgtype.Timestamptz
}

func (q *Queries) QueryAnalyticsByDateRange(ctx context.Context, db DBTX, arg QueryAnalyticsByDateRangeParams) ([]Analytic, error) {
	rows, err := db.Query(ctx, queryAnalyticsByDateRange, arg.WebsiteID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Analytic
	for rows.Next() {
		var i Analytic
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.WebsiteID,
			&i.Type,
			&i.Url,
			&i.Path,
			&i.Referrer,
			&i.Title,
			&i.Screen,
			&i.Language,
			&i.VisitorID,
			&i.SessionID,
			&i.ScrollDepth,
			&i.RealIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryDailyViews = `-- name: QueryDailyViews :one
SELECT 
    COUNT(*) as view_count
FROM analytics 
WHERE 
    website_id = $1 
    AND DATE(timestamp) = DATE($2)
	AND type='pageview'
`

type QueryDailyViewsParams struct {
	WebsiteID pgtype.UUID
	Date      interface{}
}

func (q *Queries) QueryDailyViews(ctx context.Context, db DBTX, arg QueryDailyViewsParams) (int64, error) {
	row := db.QueryRow(ctx, queryDailyViews, arg.WebsiteID, arg.Date)
	var view_count int64
	err := row.Scan(&view_count)
	return view_count, err
}

const queryDailyVisits = `-- name: QueryDailyVisits :one
SELECT 
    COUNT(DISTINCT visitor_id) as visit_count
FROM analytics 
WHERE 
    website_id = $1 
    AND DATE(timestamp) = DATE($2)
`

type QueryDailyVisitsParams struct {
	WebsiteID pgtype.UUID
	Date      interface{}
}

func (q *Queries) QueryDailyVisits(ctx context.Context, db DBTX, arg QueryDailyVisitsParams) (int64, error) {
	row := db.QueryRow(ctx, queryDailyVisits, arg.WebsiteID, arg.Date)
	var visit_count int64
	err := row.Scan(&visit_count)
	return visit_count, err
}

const queryHourlyStats = `-- name: QueryHourlyStats :many
SELECT 
  DATE_TRUNC('hour', timestamp)::timestamp AS hour,
  COUNT(id) AS views,
  COUNT(distinct session_id) as visits
FROM analytics
WHERE 
  type = 'pageview'
  AND timestamp >= NOW() - INTERVAL '24 hours'
  AND timestamp < NOW()
GROUP BY 
  DATE_TRUNC('hour', timestamp)
ORDER BY 
  hour ASC
`

type QueryHourlyStatsRow struct {
	Hour   pgtype.Timestamp
	Views  int64
	Visits int64
}

func (q *Queries) QueryHourlyStats(ctx context.Context, db DBTX) ([]QueryHourlyStatsRow, error) {
	rows, err := db.Query(ctx, queryHourlyStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryHourlyStatsRow
	for rows.Next() {
		var i QueryHourlyStatsRow
		if err := rows.Scan(&i.Hour, &i.Views, &i.Visits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
