// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_tag_connections.sql

package db

import (
	"context"
)

const deleteArticleTagConnection = `-- name: DeleteArticleTagConnection :exec
delete from article_tag_connections where id=$1
`

// DeleteArticleTagConnection
//
//	delete from article_tag_connections where id=$1
func (q *Queries) DeleteArticleTagConnection(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteArticleTagConnection, id)
	return err
}

const insertArticleTagConnection = `-- name: InsertArticleTagConnection :one
insert into
    article_tag_connections (article_id, tag_id)
values
    ($1, $2)
returning id, article_id, tag_id
`

type InsertArticleTagConnectionParams struct {
	ArticleID int32
	TagID     int32
}

// InsertArticleTagConnection
//
//	insert into
//	    article_tag_connections (article_id, tag_id)
//	values
//	    ($1, $2)
//	returning id, article_id, tag_id
func (q *Queries) InsertArticleTagConnection(ctx context.Context, db DBTX, arg InsertArticleTagConnectionParams) (ArticleTagConnection, error) {
	row := db.QueryRow(ctx, insertArticleTagConnection, arg.ArticleID, arg.TagID)
	var i ArticleTagConnection
	err := row.Scan(&i.ID, &i.ArticleID, &i.TagID)
	return i, err
}

const queryArticleTagConnection = `-- name: QueryArticleTagConnection :many
select id, article_id, tag_id from article_tag_connections
`

// QueryArticleTagConnection
//
//	select id, article_id, tag_id from article_tag_connections
func (q *Queries) QueryArticleTagConnection(ctx context.Context, db DBTX) ([]ArticleTagConnection, error) {
	rows, err := db.Query(ctx, queryArticleTagConnection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleTagConnection
	for rows.Next() {
		var i ArticleTagConnection
		if err := rows.Scan(&i.ID, &i.ArticleID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryArticleTagConnectionByID = `-- name: QueryArticleTagConnectionByID :one
select id, article_id, tag_id from article_tag_connections where id=$1
`

// QueryArticleTagConnectionByID
//
//	select id, article_id, tag_id from article_tag_connections where id=$1
func (q *Queries) QueryArticleTagConnectionByID(ctx context.Context, db DBTX, id int32) (ArticleTagConnection, error) {
	row := db.QueryRow(ctx, queryArticleTagConnectionByID, id)
	var i ArticleTagConnection
	err := row.Scan(&i.ID, &i.ArticleID, &i.TagID)
	return i, err
}

const updateArticleTagConnection = `-- name: UpdateArticleTagConnection :one
update article_tag_connections
    set article_id=$2, tag_id=$3
where id = $1
returning id, article_id, tag_id
`

type UpdateArticleTagConnectionParams struct {
	ID        int32
	ArticleID int32
	TagID     int32
}

// UpdateArticleTagConnection
//
//	update article_tag_connections
//	    set article_id=$2, tag_id=$3
//	where id = $1
//	returning id, article_id, tag_id
func (q *Queries) UpdateArticleTagConnection(ctx context.Context, db DBTX, arg UpdateArticleTagConnectionParams) (ArticleTagConnection, error) {
	row := db.QueryRow(ctx, updateArticleTagConnection, arg.ID, arg.ArticleID, arg.TagID)
	var i ArticleTagConnection
	err := row.Scan(&i.ID, &i.ArticleID, &i.TagID)
	return i, err
}

const upsertArticleTagConnection = `-- name: UpsertArticleTagConnection :one
insert into
    article_tag_connections (article_id, tag_id)
values
    ($1, $2)
on conflict (id) do update set article_id=excluded.article_id, tag_id=excluded.tag_id
returning id, article_id, tag_id
`

type UpsertArticleTagConnectionParams struct {
	ArticleID int32
	TagID     int32
}

// UpsertArticleTagConnection
//
//	insert into
//	    article_tag_connections (article_id, tag_id)
//	values
//	    ($1, $2)
//	on conflict (id) do update set article_id=excluded.article_id, tag_id=excluded.tag_id
//	returning id, article_id, tag_id
func (q *Queries) UpsertArticleTagConnection(ctx context.Context, db DBTX, arg UpsertArticleTagConnectionParams) (ArticleTagConnection, error) {
	row := db.QueryRow(ctx, upsertArticleTagConnection, arg.ArticleID, arg.TagID)
	var i ArticleTagConnection
	err := row.Scan(&i.ID, &i.ArticleID, &i.TagID)
	return i, err
}
