// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Job struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ScheduledFor   pgtype.Timestamptz
	FailedAttempts int32
	State          int32
	Instructions   []byte
	Executor       string
	RepeatableID   sql.NullString
}

type Newsletter struct {
	ID                  uuid.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Title               string
	Edition             sql.NullInt32
	Released            pgtype.Bool
	ReleasedAt          pgtype.Timestamptz
	Body                []byte
	AssociatedArticleID uuid.UUID
}

type Post struct {
	ID          uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Title       string
	Filename    string
	Slug        string
	Excerpt     string
	Draft       bool
	ReleasedAt  pgtype.Timestamp
	ReadTime    sql.NullInt32
	HeaderTitle sql.NullString
}

type PostsTag struct {
	ID     uuid.UUID
	PostID uuid.UUID
	TagID  uuid.UUID
}

type RiverJob struct {
	ID          int64
	State       RiverJobState
	Attempt     int16
	MaxAttempts int16
	AttemptedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	FinalizedAt pgtype.Timestamptz
	ScheduledAt pgtype.Timestamptz
	Priority    int16
	Args        []byte
	AttemptedBy []string
	Errors      [][]byte
	Kind        string
	Metadata    []byte
	Queue       string
	Tags        []string
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	LeaderID  string
	Name      string
}

type RiverQueue struct {
	Name      string
	CreatedAt pgtype.Timestamptz
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Subscriber struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Email        sql.NullString
	SubscribedAt pgtype.Timestamptz
	Referer      sql.NullString
	IsVerified   pgtype.Bool
}

type SubscriberToken struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	Hash         string
	ExpiresAt    pgtype.Timestamptz
	Scope        string
	SubscriberID uuid.UUID
}

type Tag struct {
	ID   uuid.UUID
	Name string
}

type Token struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	Hash      string
	ExpiresAt pgtype.Timestamptz
	Scope     string
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Name           string
	Mail           string
	MailVerifiedAt pgtype.Timestamptz
	Password       string
}
